# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hu/Projects/Rmiter-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hu/Projects/Rmiter-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hu/Projects/Rmiter-c/CMakeFiles /home/hu/Projects/Rmiter-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hu/Projects/Rmiter-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rmiter_c

# Build rule for target.
rmiter_c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rmiter_c
.PHONY : rmiter_c

# fast build rule for target.
rmiter_c/fast:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/build
.PHONY : rmiter_c/fast

cJSON/cJSON.o: cJSON/cJSON.c.o

.PHONY : cJSON/cJSON.o

# target to build an object file
cJSON/cJSON.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/cJSON/cJSON.c.o
.PHONY : cJSON/cJSON.c.o

cJSON/cJSON.i: cJSON/cJSON.c.i

.PHONY : cJSON/cJSON.i

# target to preprocess a source file
cJSON/cJSON.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/cJSON/cJSON.c.i
.PHONY : cJSON/cJSON.c.i

cJSON/cJSON.s: cJSON/cJSON.c.s

.PHONY : cJSON/cJSON.s

# target to generate assembly for a file
cJSON/cJSON.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/cJSON/cJSON.c.s
.PHONY : cJSON/cJSON.c.s

src/course.o: src/course.c.o

.PHONY : src/course.o

# target to build an object file
src/course.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course.c.o
.PHONY : src/course.c.o

src/course.i: src/course.c.i

.PHONY : src/course.i

# target to preprocess a source file
src/course.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course.c.i
.PHONY : src/course.c.i

src/course.s: src/course.c.s

.PHONY : src/course.s

# target to generate assembly for a file
src/course.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course.c.s
.PHONY : src/course.c.s

src/course_list.o: src/course_list.c.o

.PHONY : src/course_list.o

# target to build an object file
src/course_list.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course_list.c.o
.PHONY : src/course_list.c.o

src/course_list.i: src/course_list.c.i

.PHONY : src/course_list.i

# target to preprocess a source file
src/course_list.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course_list.c.i
.PHONY : src/course_list.c.i

src/course_list.s: src/course_list.c.s

.PHONY : src/course_list.s

# target to generate assembly for a file
src/course_list.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/course_list.c.s
.PHONY : src/course_list.c.s

src/ical_writer.o: src/ical_writer.c.o

.PHONY : src/ical_writer.o

# target to build an object file
src/ical_writer.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/ical_writer.c.o
.PHONY : src/ical_writer.c.o

src/ical_writer.i: src/ical_writer.c.i

.PHONY : src/ical_writer.i

# target to preprocess a source file
src/ical_writer.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/ical_writer.c.i
.PHONY : src/ical_writer.c.i

src/ical_writer.s: src/ical_writer.c.s

.PHONY : src/ical_writer.s

# target to generate assembly for a file
src/ical_writer.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/ical_writer.c.s
.PHONY : src/ical_writer.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/main.c.s
.PHONY : src/main.c.s

src/myrmit_api.o: src/myrmit_api.c.o

.PHONY : src/myrmit_api.o

# target to build an object file
src/myrmit_api.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_api.c.o
.PHONY : src/myrmit_api.c.o

src/myrmit_api.i: src/myrmit_api.c.i

.PHONY : src/myrmit_api.i

# target to preprocess a source file
src/myrmit_api.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_api.c.i
.PHONY : src/myrmit_api.c.i

src/myrmit_api.s: src/myrmit_api.c.s

.PHONY : src/myrmit_api.s

# target to generate assembly for a file
src/myrmit_api.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_api.c.s
.PHONY : src/myrmit_api.c.s

src/myrmit_parser.o: src/myrmit_parser.c.o

.PHONY : src/myrmit_parser.o

# target to build an object file
src/myrmit_parser.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_parser.c.o
.PHONY : src/myrmit_parser.c.o

src/myrmit_parser.i: src/myrmit_parser.c.i

.PHONY : src/myrmit_parser.i

# target to preprocess a source file
src/myrmit_parser.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_parser.c.i
.PHONY : src/myrmit_parser.c.i

src/myrmit_parser.s: src/myrmit_parser.c.s

.PHONY : src/myrmit_parser.s

# target to generate assembly for a file
src/myrmit_parser.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/myrmit_parser.c.s
.PHONY : src/myrmit_parser.c.s

src/parser_common.o: src/parser_common.c.o

.PHONY : src/parser_common.o

# target to build an object file
src/parser_common.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/parser_common.c.o
.PHONY : src/parser_common.c.o

src/parser_common.i: src/parser_common.c.i

.PHONY : src/parser_common.i

# target to preprocess a source file
src/parser_common.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/parser_common.c.i
.PHONY : src/parser_common.c.i

src/parser_common.s: src/parser_common.c.s

.PHONY : src/parser_common.s

# target to generate assembly for a file
src/parser_common.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/parser_common.c.s
.PHONY : src/parser_common.c.s

src/user_cli.o: src/user_cli.c.o

.PHONY : src/user_cli.o

# target to build an object file
src/user_cli.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/user_cli.c.o
.PHONY : src/user_cli.c.o

src/user_cli.i: src/user_cli.c.i

.PHONY : src/user_cli.i

# target to preprocess a source file
src/user_cli.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/user_cli.c.i
.PHONY : src/user_cli.c.i

src/user_cli.s: src/user_cli.c.s

.PHONY : src/user_cli.s

# target to generate assembly for a file
src/user_cli.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/user_cli.c.s
.PHONY : src/user_cli.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/rmiter_c.dir/build.make CMakeFiles/rmiter_c.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rmiter_c"
	@echo "... cJSON/cJSON.o"
	@echo "... cJSON/cJSON.i"
	@echo "... cJSON/cJSON.s"
	@echo "... src/course.o"
	@echo "... src/course.i"
	@echo "... src/course.s"
	@echo "... src/course_list.o"
	@echo "... src/course_list.i"
	@echo "... src/course_list.s"
	@echo "... src/ical_writer.o"
	@echo "... src/ical_writer.i"
	@echo "... src/ical_writer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myrmit_api.o"
	@echo "... src/myrmit_api.i"
	@echo "... src/myrmit_api.s"
	@echo "... src/myrmit_parser.o"
	@echo "... src/myrmit_parser.i"
	@echo "... src/myrmit_parser.s"
	@echo "... src/parser_common.o"
	@echo "... src/parser_common.i"
	@echo "... src/parser_common.s"
	@echo "... src/user_cli.o"
	@echo "... src/user_cli.i"
	@echo "... src/user_cli.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

